AWSTemplateFormatVersion: "2010-09-09"

Description: Create ALB and CloudWatchAlarm that notify ALB health status

Parameters:
# アラーム送信先のメールアドレス指定
  EmailAdress:
    Type: String
    Description: Enter EmailAdress for nortification

Resources:

#ターゲットグループ作成
  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: "TG"
      VpcId: !ImportValue VpcId
      Protocol: "HTTP"
      ProtocolVersion: "HTTP1"
      Port: 80
      TargetType: "instance"
      Targets: 
      - 
        Id: !ImportValue EC2
        Port: 80

      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher: 
        HttpCode: "200"
      Tags:
      -
        Key: "Name"
        Value: "lecture10"

#リスナー設定
  Listener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: "HTTP"
      DefaultActions: 
      - 
        TargetGroupArn: !Ref TargetGroup
        Type: "forward"

#ALB作成
  ApplicationLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: "ALBTEST"
      Scheme: "internet-facing"
      Type: "application"
      Subnets: 
      - !ImportValue Pub-SubId1
      - !ImportValue Pub-SubId2
      SecurityGroups: 
      - !ImportValue ALBsg
      IpAddressType: "ipv4"
      LoadBalancerAttributes:
        - Key: access_logs.s3.enabled
          Value: true
        - Key: access_logs.s3.bucket
          Value: !ImportValue S3Bucket
      Tags:
      -
        Key: "Name"
        Value: "lecture10"

#SNSトピック作成
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "SNS-lecture10"
      Tags: 
      - 
        Key: "Name"
        Value: "lecture10"

#サブスクリプション設定
  Subscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      TopicArn: !Ref SNSTopic
      Endpoint: !Ref EmailAdress
      Protocol: "email"

# healthyになったらOKアクション、unhealthyになったらアラームアクションでSNS経由でメール送付
  ALBHealthyHostCountFtAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref SNSTopic  
      AlarmName: ALB Health Check
      MetricName: HealthyHostCount
      Namespace: AWS/ApplicationELB
      Statistic: Average  
      Period: 60  
      EvaluationPeriods: 1  # 閾値超過回数
      Threshold: 0  # 閾値
      TreatMissingData: ignore
      OKActions:
        - !Ref SNSTopic  # 復旧時のアクション
      ComparisonOperator: LessThanOrEqualToThreshold  # 閾値以下
      Dimensions:
        - Name: TargetGroup
          Value: !GetAtt TargetGroup.TargetGroupFullName
        - Name: LoadBalancer
          Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
        - Name: AvailabilityZone
          Value: !Select 
            - 0
            - Fn::GetAZs: !Ref 'AWS::Region'